### ISSUE TITLE
Problema al hacer knit

### ISSUE THREAD

**Issue by mfeliuribas** [jvcasillas/icphs2023_rmd_template#1]
Hola Joseph! Me he descargado el zip tanto de icphs2019 como el de 2023 para empezar a formatear el trabajo final de fonética y en ambos casos, cuando hago knit del master.Rmd, me pone que hay un error. Sé que estuviste actualizando ambos repos, así que no tengo muy claro si hay algún problema con mi ordenador/r studio/etc., o si es algo del documento. Cuando tengas un momento, podrías mirarlo, por favor? 

Gracias!!

**Comment by jvcasillas** [comment]
Hola. Gracias por el comentario. Puedes explicar el error que te da? Sin esa información es difícil averiguar cuál es el problema.

**Comment by mfeliuribas** [comment]
Sí, claro! Perdona! No me crea el pdf y me sale esto de aviso:

TeX Live 2022 is frozen
and will no longer be routinely updated.  This happens when a new
release is made, or will be made shortly.

For general status information about TeX Live, see its home page:
https://tug.org/texlive

! LaTeX Error: File `colortbl.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile master.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See master.log for more info.
Execution halted

**Comment by jvcasillas** [comment]
Ok. Bien. Esto ayuda. Puede abrir el rstudio project y poner esto en la consola: `tinytex::reinstall_tinytex()`. Después de la reinstalación, cierra RStudio, vuelve a abrirlo e intenta de nuevo. Si da error de nuevo, míralo bien y dime si es diferente. Si es igual, sube aquí el archivo `main.log` (debería generar este archivo al fallar).

**Comment by mfeliuribas** [comment]
Ha funcionado!!! Mil gracias!

**Comment by jvcasillas** [comment]
¡Genial!
